### ISSUE TITLE
BF_CANONICAL_RANGE在 riscv64和aarch64 不同的问题

### ISSUE THREAD

**Issue by llh730** [rel4team/sel4_cspace#2]
在riscv64 中 BF_CANONICAL_RANGE 为 39 ， 而在 aarch64 中BF_CANONICAL_RANGE为48，导致某些即使是非aarch架构的cap的域位也不相同

**Comment by ZhiQiu-ovO** [comment]
发现在endpoint mdb 和notification中也存在这样的问题
